### ISSUE TITLE
Add support for ZIO Schema

### ISSUE THREAD

**Issue by matthewjones372** [kitlangton/neotype#3]
Awesome library! Any plans on adding a module for ZIO schema?

**Comment by kitlangton** [comment]
For sure! I'll add that to my list (though PRs are welcome as well, if you'd like to give it a whirl 😄)

**Comment by matthewjones372** [comment]
Something like this? https://github.com/kitlangton/neotype/pull/4 there's probably an easier way to test this...

**Comment by kitlangton** [comment]
Thanks Matthew!
