### ISSUE TITLE
Possible literal bug with class value for new type (v0.0.9)

### ISSUE THREAD

**Issue by gzoller** [kitlangton/neotype#7]
Code:
```scala
case class Person(name: String, age: Int)

type NonEmptyString = NonEmptyString.Type
given NonEmptyString: Newtype[String] with
  inline def validate(input: String): Boolean =
    input.nonEmpty

type MinorPerson = MinorPerson.Type
given MinorPerson: Newtype[Person] with
  inline def validate(input: Person): Boolean =
    input.age < 18

case class SampleNeo(name: NonEmptyString, label: String, unknown: MinorPerson)

val p = SampleNeo(NonEmptyString("Greg"), "MVP", MinorPerson(Person("David", 16)))
```

Got error:
  —— Newtype Error ——————————————————————————————————————————————————————————
  MinorPerson.apply requires a compile-time known Person.
  I could not parse Person("David", 16).

  🤠 Possible Solutions
  1. Try passing a literal Person:
     MinorPerson("input")
  2. Call the make method, which returns a runtime-validated Either:
     MinorPerson.make(Person("David", 16))
  3. If you are sure the input is valid, use the unsafe method:
     MinorPerson.unsafe(Person("David", 16))
  4. If you think this is a bug, please open an issue at:
     https://github.com/kitlangton/neotype/issues
  ———————————————————————————————————————————————————————————————————————————

Person here was a literal and its type should be known at compile-time in this context.  This is different than, say, this:
```scala
val person = getPersonFromSomewhere()
val p = SampleNeo(NonEmptyString("Greg"), "MVP", MinorPerson(person))
```
In this case the compiler wouldn't know--and I'd be rightly expected to need a call to make().

**Comment by kitlangton** [comment]
Ah yes, I haven't yet supported wrapping case classes in Newtypes. Usually they're used for wrapping primitives. However, that would be fun to try, and I think I can do it!

**Comment by kitlangton** [comment]
```scala
case class Person(name: String, age: Int)

type ElderlyPerson = ElderlyPerson.Type
object ElderlyPerson extends Newtype[Person]:
  override inline def validate(value: Person): Boolean =
    value.age > 65

object NewtypeExamples:
  val elder = ElderlyPerson(Person("Lazarus", 70))
  // val youth = ElderlyPerson(Person("Kit", 30))
```

![CleanShot 2024-03-07 at 18 43 40@2x](https://github.com/kitlangton/neotype/assets/7587245/5915eee2-5639-45d8-928f-83ee0c9a39ee)

**Comment by kitlangton** [comment]
Got it to work @gzoller! There are some restrictions, but it works as long as you only select fields from the case class and don't call custom methods (which it wouldn't be able to execute at compile time)
